# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("donation_received", "Donation Received"),
                            ("first_donation", "First Donation"),
                            ("pledge_created", "Pledge Created"),
                            ("pledge_updated", "Pledge Updated"),
                            ("pledge_late", "Pledge Late"),
                            ("pledge_cancelled", "Pledge Cancelled"),
                            ("contact_created", "Contact Created"),
                            ("contact_updated", "Contact Updated"),
                            ("contact_status_changed", "Contact Status Changed"),
                            ("donor_lapsed", "Donor Lapsed"),
                            ("gift_late", "Gift Late"),
                            ("at_risk", "At Risk Donor"),
                            ("task_due", "Task Due"),
                            ("task_overdue", "Task Overdue"),
                            ("task_completed", "Task Completed"),
                            ("import_completed", "Import Completed"),
                            ("user_login", "User Login"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("alert", "Alert"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("object_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False, verbose_name="read")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                ("is_new", models.BooleanField(db_index=True, default=True, verbose_name="new")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="contacts.contact",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "db_table": "events",
                "ordering": ["-created_at"],
            },
        ),
    ]
