# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user", "is_read", "created_at"], name="events_user_id_f9bda5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["user", "event_type"], name="events_user_id_026379_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["user", "is_new"], name="events_user_id_ccc282_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["contact", "created_at"], name="events_contact_ae9168_idx"),
        ),
    ]
