# Generated by Django 4.2.27 on 2026-01-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("donation_received", "Donation Received"),
                    ("first_donation", "First Donation"),
                    ("pledge_created", "Pledge Created"),
                    ("pledge_updated", "Pledge Updated"),
                    ("pledge_late", "Pledge Late"),
                    ("pledge_cancelled", "Pledge Cancelled"),
                    ("contact_created", "Contact Created"),
                    ("contact_updated", "Contact Updated"),
                    ("contact_status_changed", "Contact Status Changed"),
                    ("donor_lapsed", "Donor Lapsed"),
                    ("gift_late", "Gift Late"),
                    ("at_risk", "At Risk Donor"),
                    ("task_due", "Task Due"),
                    ("task_overdue", "Task Overdue"),
                    ("task_completed", "Task Completed"),
                    ("import_completed", "Import Completed"),
                    ("user_login", "User Login"),
                    ("journal_created", "Journal Created"),
                    ("journal_archived", "Journal Archived"),
                    ("journal_stage_event", "Journal Stage Event"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="type",
            ),
        ),
    ]
