# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pledges", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One-Time Gift"),
                            ("recurring", "Recurring Gift"),
                            ("special", "Special Gift"),
                        ],
                        default="one_time",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("check", "Check"),
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("bank_transfer", "Bank Transfer/ACH"),
                            ("other", "Other"),
                        ],
                        default="check",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference ID from external system",
                        max_length=100,
                        verbose_name="external ID",
                    ),
                ),
                (
                    "thanked",
                    models.BooleanField(db_index=True, default=False, verbose_name="thanked"),
                ),
                (
                    "thanked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="thanked at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "imported_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="imported at"),
                ),
                (
                    "import_batch",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="import batch"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="contacts.contact",
                    ),
                ),
                (
                    "pledge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="pledges.pledge",
                    ),
                ),
            ],
            options={
                "verbose_name": "donation",
                "verbose_name_plural": "donations",
                "db_table": "donations",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
