# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="thanked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="thanked_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["contact", "date"], name="donations_contact_abd892_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["date"], name="donations_date_00553e_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["thanked"], name="donations_thanked_bed82c_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["import_batch"], name="donations_import__6944e9_idx"),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id",),
                name="unique_external_donation_id",
            ),
        ),
    ]
