# Generated by Django 4.2.27 on 2026-01-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_create_import_models"),
        ("donations", "0003_alter_donation_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                help_text="Fund/account this donation is attributed to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="imports.fund",
            ),
        ),
    ]
