# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("thank_you", "Thank You"),
                            ("meeting", "Meeting"),
                            ("follow_up", "Follow Up"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="due date")),
                ("due_time", models.TimeField(blank=True, null=True, verbose_name="due time")),
                (
                    "reminder_date",
                    models.DateField(blank=True, null=True, verbose_name="reminder date"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="auto generated"),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "db_table": "tasks",
                "ordering": ["due_date", "-priority", "created_at"],
            },
        ),
    ]
