# Generated by Django 4.2.27 on 2026-01-25 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0003_add_next_step_model"),
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional journal this task belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="journals.journal",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["journal", "status"], name="tasks_journal_d17e66_idx"),
        ),
    ]
