# Generated by Django 4.2.11 on 2026-03-24 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_add_journal_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('thank_you', 'Thank You'), ('meeting', 'Meeting'), ('follow_up', 'Follow Up'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('due_date', models.DateField()),
                ('target_type', models.CharField(choices=[('all_missionaries', 'All Missionaries'), ('all_supervisors', 'All Supervisors'), ('specific_users', 'Specific Users'), ('my_team', 'My Team')], max_length=30)),
                ('recipient_ids', models.JSONField(default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'broadcast_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='tasks.broadcasttask'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['broadcast', 'status'], name='tasks_broadca_1885cf_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcasttask',
            index=models.Index(fields=['sender', '-created_at'], name='broadcast_t_sender__7105d7_idx'),
        ),
    ]
