# Generated by Django 4.2.27 on 2026-02-20 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0006_contact_external_constituent_id_and_more"),
        ("imports", "0003_importbatch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_gift_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gift ID from Raiser's Edge or external system",
                        max_length=100,
                        verbose_name="external gift ID",
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        help_text="Gift amount in cents (e.g., 10000 = $100.00)",
                        verbose_name="amount (cents)",
                    ),
                ),
                ("gift_date", models.DateField(db_index=True, verbose_name="gift date")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "donor_contact",
                    models.ForeignKey(
                        help_text="Donor who made this gift",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="contacts.contact",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fund/account this gift is attributed to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts",
                        to="imports.fund",
                    ),
                ),
            ],
            options={
                "verbose_name": "gift",
                "verbose_name_plural": "gifts",
                "db_table": "gifts",
                "ordering": ["-gift_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringGift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_gift_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Recurring gift ID from Raiser's Edge or external system",
                        max_length=100,
                        verbose_name="external gift ID",
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        help_text="Per-installment amount in cents (e.g., 10000 = $100.00)",
                        verbose_name="amount (cents)",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annually", "Semi-Annually"),
                            ("annually", "Annually"),
                            ("bimonthly", "Bimonthly"),
                            ("biweekly", "Biweekly"),
                            ("weekly", "Weekly"),
                            ("irregular", "Irregular"),
                        ],
                        max_length=20,
                        verbose_name="frequency",
                    ),
                ),
                ("start_date", models.DateField(db_index=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("held", "Held"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "donor_contact",
                    models.ForeignKey(
                        help_text="Donor who made this recurring gift commitment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_gifts",
                        to="contacts.contact",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fund/account this recurring gift is attributed to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_gifts",
                        to="imports.fund",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring gift",
                "verbose_name_plural": "recurring gifts",
                "db_table": "recurring_gifts",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Solicitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True,
                        help_text='Normalized "Last, First" for matching',
                        max_length=255,
                        verbose_name="normalized name",
                    ),
                ),
                (
                    "external_solicitor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Solicitor ID from Raiser's Edge",
                        max_length=100,
                        verbose_name="external solicitor ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked DonorCRM user account (auto-detected or manual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitor",
                "verbose_name_plural": "solicitors",
                "db_table": "solicitors",
                "ordering": ["normalized_name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringGiftCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        help_text="Amount credited to this solicitor in cents",
                        verbose_name="credit amount (cents)",
                    ),
                ),
                (
                    "recurring_gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="gifts.recurringgift",
                    ),
                ),
                (
                    "solicitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_gift_credits",
                        to="gifts.solicitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring gift credit",
                "verbose_name_plural": "recurring gift credits",
                "db_table": "recurring_gift_credits",
            },
        ),
        migrations.CreateModel(
            name="GiftCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        help_text="Amount credited to this solicitor in cents",
                        verbose_name="credit amount (cents)",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="gifts.gift",
                    ),
                ),
                (
                    "solicitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_credits",
                        to="gifts.solicitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "gift credit",
                "verbose_name_plural": "gift credits",
                "db_table": "gift_credits",
            },
        ),
        migrations.AddConstraint(
            model_name="solicitor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_solicitor_id", ""), _negated=True),
                fields=("external_solicitor_id",),
                name="unique_external_solicitor_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringgiftcredit",
            constraint=models.UniqueConstraint(
                fields=("recurring_gift", "solicitor"),
                name="unique_recurring_gift_solicitor_credit",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringgift",
            index=models.Index(
                fields=["donor_contact", "status"], name="recurring_g_donor_c_056ff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringgift",
            index=models.Index(
                fields=["status", "-created_at"], name="recurring_g_status_ac6d4a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringgift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_gift_id", ""), _negated=True),
                fields=("external_gift_id",),
                name="unique_recurring_external_gift_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="giftcredit",
            constraint=models.UniqueConstraint(
                fields=("gift", "solicitor"), name="unique_gift_solicitor_credit"
            ),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(
                fields=["donor_contact", "gift_date"], name="gifts_donor_c_182160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(fields=["gift_date"], name="gifts_gift_da_eb403a_idx"),
        ),
        migrations.AddConstraint(
            model_name="gift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_gift_id", ""), _negated=True),
                fields=("external_gift_id",),
                name="unique_external_gift_id",
            ),
        ),
    ]
