# Generated by Django 4.2.27 on 2026-02-21 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked DonorCRM user account (auto-detected or manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
