# Generated by Django 4.2.28 on 2026-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0003_migrate_donation_pledge_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "Credit Card"),
                    ("direct_deposit", "Direct Deposit"),
                    ("check", "Check"),
                ],
                help_text="Payment method: Credit Card, Direct Deposit, or Check",
                max_length=20,
                verbose_name="payment type",
            ),
        ),
    ]
