# Generated by Django 4.2.28 on 2026-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0004_gift_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "Credit Card"),
                    ("direct_deposit", "Direct Deposit"),
                    ("check", "Check"),
                    ("cash", "Cash"),
                    ("online", "Online"),
                ],
                help_text="Payment method: Credit Card, Direct Deposit, or Check",
                max_length=20,
                verbose_name="payment type",
            ),
        ),
    ]
