# Generated by Django 4.2.28 on 2026-04-02 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0005_add_cash_online_payment_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="recurring_gift",
            field=models.ForeignKey(
                blank=True,
                help_text="Source recurring gift if this is a generated recurring payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_gifts",
                to="gifts.recurringgift",
            ),
        ),
    ]
