# Generated by Django 4.2.28 on 2026-04-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0006_gift_recurring_gift_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringgift",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "Credit Card"),
                    ("direct_deposit", "Direct Deposit"),
                    ("check", "Check"),
                    ("cash", "Cash"),
                    ("online", "Online"),
                ],
                help_text="Payment method: Credit Card, Direct Deposit, Check, Cash, or Online",
                max_length=20,
                verbose_name="payment type",
            ),
        ),
    ]
