# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="phone")),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=20, verbose_name="secondary phone"),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, verbose_name="street address"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="city")),
                ("state", models.CharField(blank=True, max_length=50, verbose_name="state")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(default="USA", max_length=100, verbose_name="country"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("asked", "Asked"),
                            ("donor", "Donor"),
                            ("lapsed", "Lapsed"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="prospect",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "first_gift_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="first gift date"
                    ),
                ),
                (
                    "last_gift_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="last gift date"
                    ),
                ),
                (
                    "last_gift_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="last gift amount",
                    ),
                ),
                (
                    "total_given",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="total given"
                    ),
                ),
                ("gift_count", models.PositiveIntegerField(default=0, verbose_name="gift count")),
                (
                    "last_thanked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last thanked"),
                ),
                (
                    "needs_thank_you",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="needs thank you"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
                "db_table": "contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
