# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="contacts", to="groups.group"),
        ),
    ]
