# Generated by Django 4.2.27 on 2026-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Entity ID from external system (e.g., SPO)",
                max_length=100,
                verbose_name="external ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("owner", "external_id"),
                name="unique_contact_external_id_per_owner",
            ),
        ),
    ]
