# Generated by Django 4.2.27 on 2026-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_add_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="external_constituent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Constituent ID from Raiser's Edge",
                max_length=100,
                verbose_name="external constituent ID",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Organization name (for organization-type constituents)",
                max_length=255,
                verbose_name="organization name",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_constituent_id", ""), _negated=True),
                fields=("external_constituent_id",),
                name="unique_external_constituent_id",
            ),
        ),
    ]
