# Generated by Django 4.2.28 on 2026-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_contact_external_constituent_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospect", "Potential Donor"),
                    ("asked", "Asked"),
                    ("donor", "Donor"),
                    ("lapsed", "Lapsed"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="prospect",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
