# Generated by Django 4.2.28 on 2026-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_add_pg_trgm_and_merge_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_contact_email_per_owner",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_contact_external_id_per_owner",
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="unique_external_constituent_id",
        ),
        migrations.AlterField(
            model_name="contactmergelog",
            name="field_overrides",
            field=models.JSONField(
                default=dict, help_text="Fields auto-filled from merged contact"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(models.Q(("email", ""), _negated=True), ("is_merged", False)),
                fields=("owner", "email"),
                name="unique_contact_email_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("external_id", ""), _negated=True), ("is_merged", False)
                ),
                fields=("owner", "external_id"),
                name="unique_contact_external_id_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("external_constituent_id", ""), _negated=True), ("is_merged", False)
                ),
                fields=("external_constituent_id",),
                name="unique_external_constituent_id",
            ),
        ),
    ]
