# Generated by Django 4.2.28 on 2026-05-08 03:25

import apps.core.blind_index
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0014_encrypt_phone_and_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email_hash",
            field=apps.core.blind_index.BinaryHashField(
                blank=True, null=True, verbose_name="email hash"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_hash",
            field=apps.core.blind_index.BinaryHashField(
                blank=True, db_index=True, null=True, verbose_name="phone hash"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_secondary_hash",
            field=apps.core.blind_index.BinaryHashField(
                blank=True, db_index=True, null=True, verbose_name="phone secondary hash"
            ),
        ),
    ]
