# Generated by Django 4.2.28 on 2026-05-01 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annual_goal_cents",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Org-wide annual fundraising goal in cents. 0 means use the sum of each missionary's monthly goal * 12 instead.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Org settings",
                "verbose_name_plural": "Org settings",
                "db_table": "org_settings",
            },
        ),
    ]
