# Generated by Django 4.2.28 on 2026-05-08 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_id_snapshot", models.UUIDField(blank=True, editable=False, null=True)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("resource_type", models.CharField(blank=True, default="", max_length=64)),
                ("resource_id", models.CharField(blank=True, default="", max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=256)),
                ("status_code", models.PositiveSmallIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user making the request. NULL for anonymous.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "view_as_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "data access log",
                "verbose_name_plural": "data access log",
                "db_table": "core_dataaccesslog",
                "ordering": ["-timestamp"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["actor", "-timestamp"], name="core_dataac_actor_i_ed18ed_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_dataac_resourc_864cdb_idx",
                    ),
                    models.Index(
                        fields=["actor_id_snapshot"],
                        name="core_dataac_actor_snap_idx",
                    ),
                ],
            },
        ),
    ]
