# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for UI display",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                ("is_system", models.BooleanField(default=False, verbose_name="system group")),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "db_table": "groups",
                "ordering": ["name"],
            },
        ),
    ]
