# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, group is private to this user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"), name="unique_group_name_per_owner"
            ),
        ),
    ]
