# Generated by Django 4.2.27 on 2026-02-20 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0006_contact_external_constituent_id_and_more"),
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerIntention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("answered", "Answered"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when marked as answered",
                        null=True,
                        verbose_name="answered at",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when archived",
                        null=True,
                        verbose_name="archived at",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        help_text="Contact this prayer intention is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_intentions",
                        to="contacts.contact",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gift that triggered this prayer intention (if auto-created)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayer_intentions",
                        to="gifts.gift",
                    ),
                ),
            ],
            options={
                "verbose_name": "prayer intention",
                "verbose_name_plural": "prayer intentions",
                "db_table": "prayer_intentions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contact", "status"], name="prayer_inte_contact_494a1b_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="prayer_inte_status_a7c9e2_idx"
                    ),
                ],
            },
        ),
    ]
