# Generated by Django 4.2.27 on 2026-02-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0002_alter_solicitor_user"),
        ("prayers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayerintention",
            name="gift",
        ),
        migrations.AddField(
            model_name="prayerintention",
            name="gifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gifts that triggered this prayer intention (if auto-created)",
                related_name="prayer_intentions",
                to="gifts.gift",
            ),
        ),
    ]
