# Generated by Django 4.2.27 on 2026-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prayers", "0002_remove_prayerintention_gift_prayerintention_gifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerintention",
            name="last_prayed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last prayer for this intention",
                null=True,
                verbose_name="last prayed at",
            ),
        ),
    ]
