# Generated by Django 4.2.28 on 2026-05-06 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("feature", "Feature Request"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("resolved", "Resolved"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Page URL where the feedback was submitted from",
                        max_length=500,
                        verbose_name="page url",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Browser user agent at submission time",
                        max_length=500,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="User who submitted this feedback",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback entry",
                "verbose_name_plural": "feedback entries",
                "db_table": "feedback_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="feedback_en_status_c4569a_idx"
                    ),
                    models.Index(
                        fields=["type", "-created_at"], name="feedback_en_type_f0f59d_idx"
                    ),
                ],
            },
        ),
    ]
