# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(max_length=150, verbose_name="last name")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="phone number")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("fundraiser", "Fundraiser"),
                            ("admin", "Admin"),
                            ("finance", "Finance"),
                            ("read_only", "Read Only"),
                        ],
                        db_index=True,
                        default="fundraiser",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "monthly_goal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly support goal amount in dollars",
                        max_digits=10,
                        verbose_name="monthly support goal",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send email notifications for important events",
                        verbose_name="email notifications",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                    models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
                ],
            },
        ),
    ]
