# Generated by Django 4.2.27

from django.db import migrations, models


def rename_fundraiser_to_staff(apps, schema_editor):
    """Rename 'fundraiser' role to 'staff' in existing users."""
    User = apps.get_model('users', 'User')
    User.objects.filter(role='fundraiser').update(role='staff')


def rename_staff_to_fundraiser(apps, schema_editor):
    """Reverse: rename 'staff' role back to 'fundraiser'."""
    User = apps.get_model('users', 'User')
    User.objects.filter(role='staff').update(role='fundraiser')


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # First, update existing data
        migrations.RunPython(rename_fundraiser_to_staff, rename_staff_to_fundraiser),
        # Then, alter the field choices and default
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("finance", "Finance"),
                    ("read_only", "Read Only"),
                ],
                db_index=True,
                default="staff",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
