# Generated by Django 4.2.28 on 2026-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_fundraiser_to_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dashboard_layout",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User dashboard tile ordering preferences",
                verbose_name="dashboard layout",
            ),
        ),
    ]
