# Generated by Django 4.2.28 on 2026-03-02 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='The supervisor assigned to this user (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('finance', 'Finance'), ('read_only', 'Read Only'), ('mission_supervisor', 'Mission Supervisor')], db_index=True, default='staff', max_length=25, verbose_name='role'),
        ),
    ]
