# Generated by Django 4.2.28 on 2026-03-13 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_goal_fields_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goaljournalselection",
            options={
                "verbose_name": "goal journal selection",
                "verbose_name_plural": "goal journal selections",
            },
        ),
        migrations.AlterField(
            model_name="goaljournalselection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
