# Generated by Django 4.2.28 on 2026-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_fix_goal_cents_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("missionary", "Missionary"),
                    ("admin", "Admin"),
                    ("supervisor", "Supervisor"),
                    ("coach", "Coach"),
                ],
                db_index=True,
                default="missionary",
                max_length=25,
                verbose_name="role",
            ),
        ),
    ]
