# Generated by Django 4.2.27 on 2026-01-15 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Committed amount per frequency period",
                        max_digits=10,
                        verbose_name="amount",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("start_date", models.DateField(db_index=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "last_fulfilled_date",
                    models.DateField(blank=True, null=True, verbose_name="last fulfilled"),
                ),
                (
                    "next_expected_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="next expected"
                    ),
                ),
                (
                    "total_expected",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="total expected"
                    ),
                ),
                (
                    "total_received",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="total received"
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(db_index=True, default=False, verbose_name="is late"),
                ),
                ("days_late", models.PositiveIntegerField(default=0, verbose_name="days late")),
                (
                    "late_notified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="late notified"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "pledge",
                "verbose_name_plural": "pledges",
                "db_table": "pledges",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["contact", "status"], name="pledges_contact_0601cc_idx"),
                    models.Index(
                        fields=["status", "next_expected_date"], name="pledges_status_2daee6_idx"
                    ),
                    models.Index(fields=["is_late"], name="pledges_is_late_992d7b_idx"),
                ],
            },
        ),
    ]
