# Generated by Django 4.2.27 on 2026-01-24 22:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pledges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pledge",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Committed amount per frequency period",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="amount",
            ),
        ),
    ]
