# Generated by Django 4.2.27 on 2026-01-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_create_import_models"),
        ("pledges", "0002_alter_pledge_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pledge ID from external system (e.g., SPO)",
                max_length=100,
                verbose_name="external ID",
            ),
        ),
        migrations.AddField(
            model_name="pledge",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                help_text="Fund/account this pledge is attributed to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pledges",
                to="imports.fund",
            ),
        ),
        migrations.AddConstraint(
            model_name="pledge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id",),
                name="unique_pledge_external_id",
            ),
        ),
    ]
