"""
Shared "monthly support" calculation used by the Goal page and the Dashboard
"Monthly Support" tile.

Formula (single source of truth, agreed 2026-05-01):

    recurring_monthly = sum of monthly equivalents of active RecurringGifts
                        for the in-scope donor contacts (NOT divided by anything).

    one_time_monthly  = (sum of one-time gifts in the current fiscal year for
                        the in-scope donor contacts) / 12.
                        "One-time" means Gift.recurring_gift_id IS NULL — gifts
                        generated by an active recurring pledge are counted via
                        recurring_monthly above and must not be double-counted
                        here.

    effective_monthly_support = recurring_monthly + one_time_monthly

Callers pass a Q object describing how to filter Gift.donor_contact and
RecurringGift.donor_contact (e.g. by owner=user, or by id__in=[...]).
"""

from datetime import date
from decimal import Decimal

from django.db.models import Q, Sum
from django.utils import timezone

from apps.core.fiscal_year import fiscal_year_start
from apps.core.gift_utils import _monthly_equivalent_aggregate
from apps.gifts.models import Gift, RecurringGift, RecurringGiftStatus


def compute_monthly_support(donor_contact_filter: Q, today: date | None = None) -> dict:
    """Compute monthly support figures for a set of donor contacts.

    Args:
        donor_contact_filter: a Django Q object that filters the donor_contact
            FK on Gift / RecurringGift. The same Q is applied to both queries.
            Examples:
                Q(donor_contact__owner=user)
                Q(donor_contact_id__in=[uuid, ...])
        today: optional reference date for the fiscal-year window. Defaults to
            timezone.localdate() — same as date.today() while TIME_ZONE='UTC',
            but stays correct if the project ever moves to a US zone.

    Returns:
        dict with float values:
            recurring_monthly         active recurring monthly equivalent
            one_time_monthly          FY one-time gift total / 12
            effective_monthly_support sum of the above
            active_pledge_count       count of active RecurringGifts in scope
    """
    today = today or timezone.localdate()
    fy_start = fiscal_year_start(today)

    active_recurring = RecurringGift.objects.filter(
        donor_contact_filter,
        status=RecurringGiftStatus.ACTIVE,
    )
    recurring_monthly = float(_monthly_equivalent_aggregate(active_recurring))
    active_pledge_count = active_recurring.count()

    one_time_cents = (
        Gift.objects.filter(
            donor_contact_filter,
            recurring_gift__isnull=True,
            gift_date__gte=fy_start,
            gift_date__lte=today,
        ).aggregate(total=Sum("amount_cents"))["total"]
        or 0
    )
    one_time_monthly = float(Decimal(one_time_cents) / Decimal(100) / Decimal(12))

    effective = recurring_monthly + one_time_monthly

    return {
        "recurring_monthly": round(recurring_monthly, 2),
        "one_time_monthly": round(one_time_monthly, 2),
        "effective_monthly_support": round(effective, 2),
        "active_pledge_count": active_pledge_count,
    }
