# Generated by Django 4.2.27 on 2026-01-24 19:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_alter_contact_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Journal name (e.g., "Q1 2025 Campaign")', max_length=255, verbose_name='name')),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='Fundraising goal for this journal', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='goal amount')),
                ('deadline', models.DateField(blank=True, help_text='Target completion date', null=True, verbose_name='deadline')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('owner', models.ForeignKey(help_text='Missionary who owns this journal', on_delete=django.db.models.deletion.PROTECT, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journals',
                'db_table': 'journals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_memberships', to='contacts.contact')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_contacts', to='journals.journal')),
            ],
            options={
                'verbose_name': 'journal contact',
                'verbose_name_plural': 'journal contacts',
                'db_table': 'journal_contacts',
            },
        ),
        migrations.CreateModel(
            name='JournalStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('contact', 'Contact'), ('meet', 'Meet'), ('close', 'Close'), ('decision', 'Decision'), ('thank', 'Thank'), ('next_steps', 'Next Steps')], db_index=True, help_text='Pipeline stage where event occurred', max_length=20, verbose_name='stage')),
                ('event_type', models.CharField(choices=[('call_logged', 'Call Logged'), ('email_sent', 'Email Sent'), ('text_sent', 'Text Sent'), ('letter_sent', 'Letter Sent'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed'), ('ask_made', 'Ask Made'), ('follow_up_scheduled', 'Follow-up Scheduled'), ('follow_up_completed', 'Follow-up Completed'), ('decision_received', 'Decision Received'), ('thank_you_sent', 'Thank You Sent'), ('next_step_created', 'Next Step Created'), ('note_added', 'Note Added'), ('other', 'Other')], db_index=True, help_text='Type of event/action', max_length=30, verbose_name='event type')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this event', verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data (task ID, contact method, etc.)', verbose_name='metadata')),
                ('journal_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='journals.journalcontact')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_stage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'journal stage event',
                'verbose_name_plural': 'journal stage events',
                'db_table': 'journal_stage_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journal_contact', 'stage', 'created_at'], name='journal_sta_journal_b4ecfe_idx'), models.Index(fields=['journal_contact', 'created_at'], name='journal_sta_journal_284d65_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='journalcontact',
            index=models.Index(fields=['journal', 'contact'], name='journal_con_journal_ad2fec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalcontact',
            unique_together={('journal', 'contact')},
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['owner', 'is_archived'], name='journals_owner_i_335f24_idx'),
        ),
    ]
