# Generated by Django 4.2.27 on 2026-01-24 23:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pledged amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="amount",
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("one_time", "One-Time"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="cadence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "journal_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="journals.journalcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "decision",
                "verbose_name_plural": "decisions",
                "db_table": "journal_decisions",
            },
        ),
        migrations.CreateModel(
            name="DecisionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_fields",
                    models.JSONField(
                        help_text="Mapping of field names to old values before change",
                        verbose_name="changed fields",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="journals.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "decision history",
                "verbose_name_plural": "decision histories",
                "db_table": "journal_decision_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["decision", "-created_at"], name="journal_dec_decisio_cda205_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("journal_contact",), name="unique_decision_per_journal_contact"
            ),
        ),
    ]
