# Generated by Django 4.2.27 on 2026-01-25 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0002_decision_decisionhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the next step",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional additional details", verbose_name="notes"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional target completion date",
                        null=True,
                        verbose_name="due date",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(db_index=True, default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in checklist (lower = first)",
                        verbose_name="display order",
                    ),
                ),
                (
                    "journal_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_steps",
                        to="journals.journalcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "next step",
                "verbose_name_plural": "next steps",
                "db_table": "journal_next_steps",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["journal_contact", "completed"],
                        name="journal_nex_journal_03911f_idx",
                    )
                ],
            },
        ),
    ]
