# Generated by Django 4.2.28 on 2026-03-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0003_add_next_step_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalstageevent",
            name="stage",
            field=models.CharField(
                choices=[
                    ("contact", "Contact"),
                    ("scheduled", "Scheduled"),
                    ("meet", "Meet"),
                    ("close", "Close"),
                    ("decision", "Decision"),
                    ("thank", "Thank"),
                    ("next_steps", "Next Steps"),
                ],
                db_index=True,
                help_text="Pipeline stage where event occurred",
                max_length=20,
                verbose_name="stage",
            ),
        ),
    ]
