# Generated by Django 4.2.28 on 2026-04-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0004_add_scheduled_stage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(fields=["created_at"], name="journal_dec_created_f78c5c_idx"),
        ),
        migrations.AddIndex(
            model_name="journalstageevent",
            index=models.Index(fields=["created_at"], name="journal_sta_created_54411d_idx"),
        ),
    ]
