# Generated by Django 4.2.28 on 2026-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0005_add_created_at_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="journalcontact",
            index=models.Index(
                fields=["contact", "created_at"], name="journal_con_contact_b9c00f_idx"
            ),
        ),
    ]
