# Generated by Django 4.2.28 on 2026-06-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0007_encrypt_pii_phase_3a"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="follow_up_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the unfulfilled-pledge follow-up Task was created (idempotency guard).",
                null=True,
                verbose_name="follow-up created at",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["status", "follow_up_created_at"], name="journal_dec_status_b8970a_idx"
            ),
        ),
    ]
