# Generated by Django 4.2.28 on 2026-06-29 21:05

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0008_decision_follow_up_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="goal_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monthly fundraising goal for this journal",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="goal amount",
            ),
        ),
    ]
