# Generated by Django 4.2.28 on 2026-07-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_broadcasttask'),
        ('journals', '0009_alter_journal_goal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='follow_up_task',
            field=models.ForeignKey(blank=True, help_text='The live follow-up Task for this pledge, if any. Set together with follow_up_created_at; both are cleared by release_followup() when the Task is deleted. Invariant: follow_up_created_at is set iff this points at a live Task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task'),
        ),
    ]
