# Generated by Django 4.2.27 on 2026-01-30 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("funds", "Funds"),
                            ("entities", "Entities"),
                            ("transactions", "Transactions"),
                            ("pledges", "Pledges"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="import type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("validated", "Validated"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                ("total_rows", models.IntegerField(default=0, verbose_name="total rows")),
                ("created_count", models.IntegerField(default=0, verbose_name="created count")),
                ("updated_count", models.IntegerField(default=0, verbose_name="updated count")),
                ("skipped_count", models.IntegerField(default=0, verbose_name="skipped count")),
                ("error_count", models.IntegerField(default=0, verbose_name="error count")),
                (
                    "error_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict with sample errors for preview",
                        verbose_name="error summary",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "import run",
                "verbose_name_plural": "import runs",
                "db_table": "import_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.IntegerField(verbose_name="row number")),
                (
                    "error_messages",
                    models.JSONField(
                        help_text="List of error strings for this row",
                        verbose_name="error messages",
                    ),
                ),
                (
                    "row_data",
                    models.JSONField(
                        help_text="Original CSV row as dict for error CSV download",
                        verbose_name="row data",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_errors",
                        to="imports.importrun",
                        verbose_name="import run",
                    ),
                ),
            ],
            options={
                "verbose_name": "import row error",
                "verbose_name_plural": "import row errors",
                "db_table": "import_row_errors",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Fund ID from SPO system",
                        max_length=100,
                        unique=True,
                        verbose_name="external ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="fund name")),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="active, inactive, or closed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner if fund is user-specific, null for org-wide funds",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "fund",
                "verbose_name_plural": "funds",
                "db_table": "funds",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(
                fields=["uploaded_by", "-created_at"], name="import_runs_uploade_0187ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(fields=["type", "status"], name="import_runs_type_235d0d_idx"),
        ),
        migrations.AddIndex(
            model_name="importrowerror",
            index=models.Index(
                fields=["import_run", "row_number"], name="import_row__import__c1abbe_idx"
            ),
        ),
    ]
