# Generated by Django 4.2.27 on 2026-02-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imports", "0001_create_import_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MPDUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("file_format", models.CharField(max_length=10)),
                ("total_rows", models.IntegerField(default=0)),
                ("matched_count", models.IntegerField(default=0)),
                ("unmatched_count", models.IntegerField(default=0)),
                ("unmatched_rows", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mpd_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mpd_uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MPDSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_recurring_gifts",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "annual_gifts",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "monthly_average",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "annual_mpd_estimate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "mpd_standard",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "amount_below_mpd_standard",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "mpd_maximum",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "amount_above_below_maximum",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "latest_roll_forward_balance",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "current_mpd_cap",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "proj_monthly_deduction_rfb",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "pay_forecast_12_months",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "pay_forecast_over_fy",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "total_one_time_gifts_april",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("pct_standard_to_max", models.IntegerField(blank=True, null=True)),
                ("met_mpd_standard", models.BooleanField(null=True)),
                ("met_maximum", models.BooleanField(null=True)),
                ("match_met", models.BooleanField(null=True)),
                ("match_met_rest_fy", models.BooleanField(null=True)),
                ("months_remaining_rf", models.CharField(blank=True, default="", max_length=20)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="imports.mpdupload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpd_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mpd_snapshots",
                "ordering": ["-upload__created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="mpd_snapsho_user_id_43d112_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mpdsnapshot",
            constraint=models.UniqueConstraint(
                fields=("user", "upload"), name="unique_snapshot_per_user_per_upload"
            ),
        ),
    ]
