# Generated by Django 4.2.27 on 2026-02-20 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imports", "0002_mpd_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("re_constituent", "RE Constituent"),
                            ("re_solicitor", "RE Solicitor"),
                            ("re_gift", "RE Gift"),
                            ("re_recurring_gift", "RE Recurring Gift"),
                            ("generic_contacts", "Generic Contacts"),
                            ("generic_donations", "Generic Donations"),
                            ("smartsheet_mpd", "Smartsheet MPD"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="import type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("duplicate", "Duplicate (already processed)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                (
                    "sha256_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hex digest for duplicate detection",
                        max_length=64,
                        verbose_name="SHA256 hash",
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0, verbose_name="total rows")),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="created count"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="updated count"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="skipped count"),
                ),
                ("error_count", models.PositiveIntegerField(default=0, verbose_name="error count")),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific import metadata and results",
                        verbose_name="summary",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "import batch",
                "verbose_name_plural": "import batches",
                "db_table": "import_batches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_by", "-created_at"], name="import_batc_uploade_235779_idx"
                    ),
                    models.Index(
                        fields=["import_type", "status"], name="import_batc_import__317f93_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("import_type", "sha256_hash"), name="unique_import_batch_hash_per_type"
            ),
        ),
    ]
