# Generated by Django 4.2.28 on 2026-03-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imports", "0003_importbatch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("re_constituent", "RE Constituent"),
                    ("re_solicitor", "RE Solicitor"),
                    ("re_gift", "RE Gift"),
                    ("re_recurring_gift", "RE Recurring Gift"),
                    ("generic_contacts", "Generic Contacts"),
                    ("generic_donations", "Generic Donations"),
                    ("smartsheet_mpd", "Smartsheet MPD"),
                    ("spo_missionary", "SPO Missionary Reconciliation"),
                    ("spo_gift", "SPO Gift Import"),
                    ("spo_prayer", "SPO Prayer Import"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="import type",
            ),
        ),
        migrations.CreateModel(
            name="MissionaryAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name as it appears in SPO CSV export",
                        max_length=255,
                        unique=True,
                        verbose_name="source name",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional admin notes")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved missionary. Null = unresolved.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "missionary alias",
                "verbose_name_plural": "missionary aliases",
                "db_table": "missionary_aliases",
            },
        ),
    ]
