# Generated by Django 4.2.28 on 2026-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_add_missionary_alias_spo_batch_types'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='unique_import_batch_hash_per_type',
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('import_type__in', ['generic_contacts', 'generic_donations'])), fields=('import_type', 'sha256_hash', 'uploaded_by'), name='unique_generic_import_hash_per_uploader'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('import_type__in', ['generic_contacts', 'generic_donations']), _negated=True), fields=('import_type', 'sha256_hash'), name='unique_import_batch_hash_per_type'),
        ),
    ]
